- name: zookeeperd
  become: yes
  apt: name={{item}} state=latest
  with_items:
    - zookeeperd

- name: Creates zookeeper root directory {{ zookeeper_root_dir }}
  file: path={{zookeeper_root_dir}}/src state=directory owner=zookeeper
 
- name: Creates zookeeper data directory {{ zookeeper_data_dir }}
  file: path={{zookeeper_data_dir}}/src state=directory owner=zookeeper

- name: Creates zookeeper data log directory {{ zookeeper_data_log_dir }}
  file: path={{zookeeper_data_log_dir}}/src state=directory owner=zookeeper

- name: set myid
  template: src=myid dest="/etc/zookeeper/conf/myid"
  notify: restart zookeeperd
  
- name: write configuration
  template: src=zoo.cfg dest="/etc/zookeeper/conf/zoo.cfg"
  notify: restart zookeeperd

  
#- name: download jolokia {{ jolokia_version }}  
#  get_url: 
#    url: https://github.com/rhuss/jolokia/releases/download/v{{jolokia_version}}/jolokia-{{jolokia_version}}-bin.tar.gz  
#    dest: /tmp/jolokia-{{jolokia_version}}-bin.tar.gz
 
#THIS SHOULD WORK BUT SOMETHING IS BROKJEN IN ANSIBLE - GITHUB CERTS FAILS TO VALIDATE
#- name: install jolokia {{ jolokia_version }}  
#  unarchive: 
#    src: https://github.com/rhuss/jolokia/releases/download/v{{jolokia_version}}/jolokia-{{jolokia_version}}-bin.tar.gz 
#    dest: /usr/share/java 
#    remote_src: yes
#    creates: /usr/share/java/jolokia-{{jolokia_version}}/agents/jolokia-jvm.jar

#PATCH FOLR ABOVE
- name: download jolokia {{ jolokia_version }}  
  shell: wget -O /tmp/jolokia-{{jolokia_version}}-bin.tar.gz https://github.com/rhuss/jolokia/releases/download/v{{jolokia_version}}/jolokia-{{jolokia_version}}-bin.tar.gz

- name: install jolokia {{ jolokia_version }}  
  unarchive: 
    src: /tmp/jolokia-{{jolokia_version}}-bin.tar.gz
    dest: /usr/share/java 
    creates: /usr/share/java/jolokia-{{jolokia_version}}/agents/jolokia-jvm.jar


- name: update start script
  template: src=init.d.zookeeper dest="/etc/init.d/zookeeper"
  notify: restart zookeeperd
  


