---
- name: install debian prerequsites
  package: name={{ item }} state=latest
  become: true  
  with_items:
    - adduser
    - libfontconfig        

- name: download {{grafana_deb_url}}
  get_url: url={{grafana_deb_url}} dest=/tmp/grafana-{{grafana_version}}.deb

- name: install apt package of grafana from local file
  apt: deb=/tmp/grafana-{{grafana_version}}.deb
  notify:
    - restart grafana

- name: configure grafana
  template: src=grafana.ini dest=/etc/grafana/grafana.ini
  notify: restart grafana

- name: "make sure the service is running and enabled"
  service: "name=grafana-server state=running enabled=yes"
