---
# defaults file for ansible-telegraf

telegraf_agent_version: 1.3.1
telegraf_deb_url:  https://dl.influxdata.com/telegraf/releases/telegraf_{{ telegraf_agent_version }}-1_amd64.deb
telegraf_deb_package: telegraf_{{ telegraf_agent_version }}-1_amd64.deb  

telegraf_agent_hostname: "{{ ansible_fqdn }}"
telegraf_agent_interval: 10
telegraf_agent_debug: False
telegraf_agent_round_interval: True
telegraf_agent_flush_interval: 10
telegraf_agent_flush_jitter: 0

#v0.13 settings (not sure if supported in older version):
telegraf_agent_collection_jitter: 0
telegraf_agent_metric_batch_size: 1000
telegraf_agent_metric_buffer_limit: 10000
telegraf_agent_quiet: False

#v1.1 settings:
telegraf_agent_logfile: ""
telegraf_agent_omit_hostname: False

telegraf_agent_tags:

telegraf_agent_output:
  - type: influxdb
    config:
      - urls = ["http://localhost:8086"]
      - database = "telegraf"
      - precision = "s"

telegraf_plugins_default:
  - plugin: cpu
    config:
      - percpu = true
  - plugin: disk
  - plugin: io
  - plugin: mem
  - plugin: net
  - plugin: system
  - plugin: swap
  - plugin: netstat

telegraf_plugins_extra:
