
- name: Install add-apt-repostory
  apt: name=software-properties-common state=latest
  become: yes

- name: Add Oracle Java Repository
  apt_repository: repo='ppa:webupd8team/java'
  become: yes

- name: Install OpenJDK Java 8
  apt: name={{item}} state=latest
  become: yes
  with_items:
    - openjdk-8-jre 
    - openjdk-8-jdk

- name: Set JAVA_HOME
  lineinfile: dest=/etc/environment state=present regexp='^JAVA_HOME' line='JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64/'
  become: yes



