- hosts: all
  gather_facts: false
  become: true
  tasks:
    - name: Install python for Ansible
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)

- hosts: all
  gather_facts: false
  become: true
  tasks:
    - name: Install aptitude for Ansible
      raw: test -e /usr/bin/aptitude || (apt -y update && apt install -y aptitude)

- hosts: all
  gather_facts: true

- hosts: all
  gather_facts: false
  become: true
  tasks:
    - apt_key: url=https://download.docker.com/linux/ubuntu/gpg state=present
    - apt_key: url=https://packages.cloud.google.com/apt/doc/apt-key.gpg state=present
    - apt_key: keyserver=hkp://keyserver.ubuntu.com:80 id=382E94DE state=present
    - apt_repository: repo={{ item }} state=present
      with_items:
        - deb http://us.archive.ubuntu.com/ubuntu/ bionic main restricted
        - deb http://us.archive.ubuntu.com/ubuntu/ bionic-updates main restricted
        - deb http://us.archive.ubuntu.com/ubuntu/ bionic universe
        - deb http://us.archive.ubuntu.com/ubuntu/ bionic-updates universe
        - deb http://us.archive.ubuntu.com/ubuntu/ bionic multiverse
        - deb http://us.archive.ubuntu.com/ubuntu/ bionic-updates multiverse
        - deb http://us.archive.ubuntu.com/ubuntu/ bionic-backports main restricted universe multiverse
        - deb http://security.ubuntu.com/ubuntu bionic-security main restricted
        - deb http://security.ubuntu.com/ubuntu bionic-security universe
        - deb http://security.ubuntu.com/ubuntu bionic-security multiverse
        - deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
        - deb http://apt.kubernetes.io/ kubernetes-xenial main
        - deb https://apt.datadoghq.com/ stable 6
    - stat: path=/etc/cloud/cloud.cfg
      register: cloud_config
    - lineinfile: 'dest=/etc/cloud/cloud.cfg state=present regexp="^preserve_hostname:" line="preserve_hostname: true"'
      when: cloud_config.stat.exists == True
    - mount: name=swap fstype=swap state=absent
    - command: swapoff -a
      when: ansible_swaptotal_mb > 0
    - apt: update_cache=yes upgrade=yes
    - package: name={{ item }} state=latest
      with_items:
       - ntp
       - htop
       - iftop
       - bmon
       - apt-transport-https
       - ca-certificates
       - curl
       - software-properties-common
       - intel-microcode
       - openvpn
       - openjdk-11-jre 
       - openjdk-11-jdk
       - libpam-u2f
       - kubectl
       - traceroute
       - autoconf 
       - automake 
       - autogen 
       - build-essential 
       - cmake
       - ninja-build 
       - ccache
       - net-tools
       - docker-ce
       - python3-pip
       - python-pip
       - pax-utils 
       - shtool 
       - libtool 
       - unzip 
       - pkg-config 
       - sed 
       - python 
       - openssh-server 
       - rsync 
    - pip: name=docker
    - group: name=sudo state=present
    - group: name=wheel state=present
    - user: name=gitlab-runner shell=/bin/bash groups=adm,sudo,wheel,docker append=yes
    - user: name={{ ansible_user }} shell=/bin/bash groups=adm,sudo,wheel,docker append=yes
    - lineinfile: "dest=/etc/sudoers state=present line='%sudo ALL=(ALL) NOPASSWD: ALL'"
    - sysctl: name=fs.inotify.max_user_watches value=524288
    - sysctl: name=vm.max_map_count value=262144


