- hosts: all
  gather_facts: true
  become: true
  tasks:
    - apt_key: url=https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/7fa2af80.pub state=present
    - apt_key: url=https://nvidia.github.io/nvidia-docker/gpgkey state=present
    - apt_repository: repo={{ item }} state=present
      with_items:
        - ppa:graphics-drivers/ppa
    - get_url: url=https://nvidia.github.io/nvidia-docker/ubuntu18.04/nvidia-docker.list dest=/etc/apt/sources.list.d/nvidia-docker.list
    - apt: update_cache=yes upgrade=yes autoremove=yes
    - package: name={{ item }} state=latest
      with_items:
       - build-essential 
       - dkms
       - freeglut3 
       - freeglut3-dev 
       - libxi-dev 
       - libxmu-dev
       - git 
       - curl 
       - autoconf 
       - build-essential 
       - ncurses-dev 
       - libssl-dev
    - apt: deb=https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/cuda-repo-ubuntu1804_10.0.130-1_amd64.deb
    - apt: update_cache=yes
    - package: name={{ item }} state=latest
      with_items:
       - cuda
       - nvidia-container-toolkit



