- hosts: all
  gather_facts: yes

- hosts: all
  become: true
  roles:
     - tensorflow_no_gpu

#TBD compile bazel from source since it does not seems to work from packages.
#TBD build tensorflow using basel
	 
