# file: roles/kafka/tasks/main.yml

- name: Make sure the kafka group is present
  action: group name={{ kafka_group }} state=present

- name: Make sure the kafka user directory is present 
  file: path="/app/home/{{ kafka_user }}" state=directory

- name: Make sure the kafka user is present
  user: name={{ kafka_user }} group={{ kafka_group }} home="/app/home/{{ kafka_user }}" shell=/bin/bash state=present comment="Kafka user"
  
- name: Creates src directory {{ kafka_root_dir }}/src
  file: path={{ kafka_root_dir }}/src state=directory

- name: Creates config directory
  file: path="{{ kafka_root_dir }}/config" state=directory

- name: create log directories
  file: path={{ item }} state=directory owner={{ kafka_user }} group={{ kafka_group }} mode=0750 recurse=yes
  with_items: "{{ kafka_log_dirs }}"

- name: download jolokia {{ jolokia_version }}  
  get_url: 
    url: https://github.com/rhuss/jolokia/releases/download/v{{jolokia_version}}/jolokia-{{jolokia_version}}-bin.tar.gz  
    dest: /tmp/jolokia-{{jolokia_version}}-bin.tar.gz
 
- name: unarchive jolokia {{ jolokia_version }}  
  unarchive: 
    src: /tmp/jolokia-{{jolokia_version}}-bin.tar.gz  
    dest: /usr/share/java 
    creates: /usr/share/java/jolokia-{{jolokia_version}}/agents/jolokia-jvm.jar
    
- name: download kafka {{ kafka_full_version }}
  get_url: url={{ kafka_download_url }} dest={{ kafka_root_dir }}/src/kafka_{{ kafka_full_version }}.tgz
  
- command: chdir={{ kafka_root_dir }} tar xzf {{ kafka_root_dir }}/src/kafka_{{ kafka_full_version }}.tgz creates={{ kafka_root_dir }}/kafka_{{ kafka_full_version }}/bin/kafka-server-start.sh

- name: Update the symbolic link to the kafka install
  file: path={{ kafka_root_dir }}/kafka src={{ kafka_root_dir }}/kafka_{{ kafka_full_version }} state=link force=yes
  notify:
    - restart kafka
#    - restart-kafka-delay

- name: Update the configuration
  template: src=server.properties dest={{ kafka_root_dir }}/config/server.properties owner={{ kafka_user }} group={{ kafka_group }} mode=0644
  notify:
    - restart kafka
#    - restart-kafka-delay

- name: " kafka-broker - replace start script"
  template: src=kafka-server-start.sh dest="{{ kafka_root_dir }}/kafka/bin/kafka-server-start.sh" owner="{{ kafka_user }}" group="{{ kafka_group }}" mode=0774
  notify:
    - restart kafka
#    - restart-kafka-delay

- name: Update the install permissions of kafka
  file: path={{ kafka_root_dir }}/kafka_{{ kafka_full_version }} owner={{ kafka_user }} group={{ kafka_group }} state=directory recurse=yes
 
- name: Update the install permissions of jolokia
  file: path={{ kafka_root_dir }}/jolokia-{{ jolokia_version }} owner={{ kafka_user }} group={{ kafka_group }} state=directory recurse=yes
 
- name: systemd start script
  template: src=kafka-broker.service dest=/etc/systemd/system/kafka-broker.service owner=root group=root mode=644 
  notify: 
    - reload systemd
    - restart kafka
#    - restart-kafka-delay    

- name: "make sure the service is running and enabled"
  service: "name=kafka-broker state=started enabled=yes"

 
