- name: install debian prerequsites
  package: name={{ item }} state=latest
  become: true  
  with_items:
    - xz-utils
    - python-pip

- name: download arduino ide
  get_url: url={{arduino_ide_url}} dest=~/arduino-{{ arduino_ide_version }}-linux64.tar.xz
  
#- name: download arduino ide  
#  unarchive:
#    src: "{{ arduino_ide_url }}"
#    dest: /opt
#    remote_src: True

- name: extract arduino ide
  shell: tar xvf arduino-{{ arduino_ide_version }}-linux64.tar.xz
  args:
    chdir: ~/
    creates: ~/arduino-{{ arduino_ide_version }}

- name: install pyserial
  pip: name=pyserial
  become: true


- name: create expressif dir
  file:
    path: ~/arduino-{{ arduino_ide_version }}/hardware/espressif
    state: directory
    mode: 0755


- name: checkout esp32 files
  git:
    repo: 'https://github.com/espressif/arduino-esp32.git'
    dest: ~/arduino-{{ arduino_ide_version }}/hardware/espressif/esp32

- name: download espressif tools
  shell: python get.py
  args:
    chdir: ~/arduino-{{ arduino_ide_version }}/hardware/espressif/esp32/tools
 #   creates: ~/arduino-{{ arduino_ide_version }}/hardware/espressif/esp32/tools/dist

