
- name: Install add-apt-repostory
  apt: name=software-properties-common state=latest
  become: yes

- name: Add Oracle Java Repository
  apt_repository: repo='ppa:webupd8team/java'
  become: yes

#- name: Purge Oracle / openjdk Java 8
#  apt: name={{item}} state=absent
#  become: yes
#  with_items:
#    - oracle-java8-installer
#    - oracle-java8-set-default
#    - openjdk-8-jre 
#    - openjdk-8-jdk
  
#- name: Accept Java 9 Licence
#  shell: echo oracle-java9-installer shared/accepted-oracle-license-v1-1 select true | tee /etc/oracle-java-9-licence-acceptance | /usr/bin/debconf-set-selections
#  become: yes
#  args:
#    creates: /etc/oracle-java-9-licence-acceptance
        
#- name: Install Oracle Java 9
#  apt: name={{item}} state=latest
#  become: yes
#  with_items:
#    - oracle-java9-installer
#    - ca-certificates
#    - oracle-java9-set-default


- name: Install OpenJDK Java 8
  apt: name={{item}} state=latest
  become: yes
  with_items:
    - openjdk-8-jre 
    - openjdk-8-jdk

- name: Set JAVA_HOME
  lineinfile: dest=/etc/environment state=present regexp='^JAVA_HOME' line='JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64/'
  become: yes


#- name: Install OpenJDK Java 9
#  apt: name={{item}} state=latest
#  become: yes
#  with_items:
#    - openjdk-9-jre 
#    - openjdk-9-jdk

#- name: Set JAVA_HOME
#  lineinfile: dest=/etc/environment state=present regexp='^JAVA_HOME' line='JAVA_HOME=/usr/lib/jvm/java-9-openjdk-amd64/'
#  become: yes
