- name: install tensorflow prerequsites
  sudo: yes
  apt: pkg={{ item }} update_cache=yes
  
  with_items:
    - python-pip
    - python-dev
    - python-numpy 
    - python-wheel	

#1 we nee to build bazel from source
#2 build tensorflow from source

#- name: install tensorflow	
#  pip:
#    name: tensorflow
