- name: reload systemd
  sudo: yes
  command: systemctl daemon-reload

- name: restart kafka
  service: name=kafka-broker state=restarted enabled=yes
#  service: name=kafka-broker state=restarted enabled=yes daemon_reload=yes sleep=60
  
#- name: restart-kafka-delay
#  pause: seconds=30
