- name: add confluent signing key
  apt_key: url=http://packages.confluent.io/deb/3.0/archive.key state=present  
  
- name: add confluent repo
  apt_repository: repo='deb http://packages.confluent.io/deb/3.0 stable main' state=present  
  
- name: update apt packages
  apt: update_cache=yes upgrade=yes

- name: install packages
  apt: pkg={{ item }}
  with_items:
   - confluent-schema-registry

- file: path=/etc/kafka/schema-registry.properties state=absent

- file: path=/etc/confluent-schema-registry state=directory owner={{ kafka_user }} group={{ kafka_group }}
   
- name: systemd start script
  template: src=confluent-schema-registry.service dest=/etc/systemd/system/confluent-schema-registry.service owner=root group=root mode=644 
  notify: 
   - reload systemd     
   - restart confluent-schema-registry

- name: Update the configuration
  template: src=schema-registry.properties dest=/etc/confluent-schema-registry/schema-registry.properties owner={{ kafka_user }} group={{ kafka_group }} mode=0644
  notify:
    - restart confluent-schema-registry
  
- name: "make sure the confluent-schema-registry is running and enabled"
  service: "name=confluent-schema-registry state=started enabled=yes"
